image: 16-alpine3.16

stages:
  - deploy

deploy:
  stage: deploy
  allow_failure: false
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - node_modules
      - package-lock.json
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm run build && npm publish
